Add support for exporting to influxdb v2.
hassio-addons/addon-glances pull request #217
Opened 2021-10-15 12:36 UTC by hnefatl

# Proposed Changes

Add configuration options+change influxdb service script to support Glances writing to an InfluxDB 2.x database.

I've tested this using a local addon, and was able to write to both a v1 database (the influxdb HA addon) and a v2 database (an external database running on a different host) at the same time, as well as just writing to one with the other disabled.

Question: I'm not familiar with how existing configurations are handled with addon upgrades: I've added some _required_ fields in this commit, does that mean everyone who upgrades to a version including this commit will need to update their configs to set the required fields to something? Or will HA somehow merge the configs when updating so people won't notice the change? This option set felt best as a separate dictionary, but that means the change isn't really backwards- or forwards- compatible.

## Related Issues

- https://github.com/hassio-addons/addon-glances/issues/205

2021-11-06 13:44 UTC, hnefatl commented
Bump for review: there's one failing check for a missing PR label, but I don't see a way to apply one to this PR. Assuming I don't have permissions? I'd assume the `enhancement` tag is the most fitting here.

2021-12-07 09:49 UTC, hnefatl commented
Bump for review again, see note about PR labels above.

2021-12-20 11:03 UTC, frenck requested changes

2021-12-20 11:03 UTC, frenck commented on glances/rootfs/etc/services.d/influxdb/run
> +    fi
These are now added twice, when both influxdb1 & 2 are enabled

2021-12-20 11:03 UTC, frenck commented on glances/rootfs/etc/services.d/influxdb/run
> +    glances_export "influxdb" "$(bashio::config 'influxdb.interval')" &
We should not drop things in the background.

2021-12-20 11:03 UTC, frenck commented on glances/rootfs/etc/services.d/influxdb/run
> +    glances_export "influxdb2" "$(bashio::config 'influxdb2.interval')" &
Same comment as above.

2021-12-20 11:03 UTC, frenck commented on glances/rootfs/etc/services.d/influxdb/run
> +    options+=(--export "$influxdb_version")
If both options are enabled, the influxdb2 process will export both v1 & v2, while v1 is also active.

2022-01-27 08:20 UTC, closed without merging