Add gcc build dependency
hassio-addons/addon-glances pull request #280
Opened 2022-09-05 20:22 UTC by tjorim

# Proposed Changes

Add gcc build dependency, which seems needed to build the psutil requirement

## Related Issues

Needed for #279

2022-09-18 19:49 UTC, frenck requested changes

2022-09-18 19:49 UTC, frenck commented on glances/Dockerfile
> +        gcc=11.2.1_git20220219-r2 \
This is lower maintenance (changes way less often, as it is a meta package), and also provides gcc.

```suggestion
        build-base=0.5-r3 \
```

2022-09-19 07:25 UTC, frenck approved these changes
Thanks, @tjorim 👍

2022-09-19 07:25 UTC, merged

2022-09-19 07:51 UTC, tjorim commented
Ugh, why don't they have the prebuilt we need anymore. Looks like it also wants `python3-dev` now.

2022-09-19 07:53 UTC, frenck commented
> Ugh, why don't they have the prebuilt we need anymore. Looks like it also wants python3-dev now.

Our base images also pick up Home Assistant wheels (https://wheels.home-assistant.io), that is the reason it now needs a bit more (as HA hasn't bumped yet).

2022-09-19 08:04 UTC, tjorim commented
Oh I see, I expected the build to check home assistant wheels in addition to pypi. So if a PR is merged in HA core to bump psutil (used for systemmonitor), the wheels for that will also be build.

2022-09-19 08:23 UTC, frenck commented
> So if a PR is merged in HA core to bump psutil (used for systemmonitor), the wheels for that will also be build?

Yes!